src/components/organisms/Team/team_members.js
src/markdown/team/lyons-james.md

Will update headshot once it's taken.

Add James to team

---

src/components/atoms/ContainerMarkdown/index.js
src/components/atoms/ContainerMarkdown/styles.module.scss
src/components/atoms/index.js
src/components/molecules/SiteCredits/index.js
src/components/molecules/SiteCredits/styles.module.scss
src/components/molecules/SocialIcons/index.js
src/components/molecules/SocialIcons/styles.module.scss
src/components/molecules/index.js
src/components/organisms/Footer/index.js
src/components/organisms/Footer/styles.module.scss
src/components/organisms/FooterMarkdown/index.js
src/components/organisms/FooterMarkdown/styles.module.scss
src/components/organisms/Sidebar/index.js
src/components/organisms/Sidebar/styles.module.scss
src/components/organisms/index.js
src/components/templates/Blueprints/index.js
src/components/templates/Blueprints/styles.module.scss
src/markdown/blueprints/principles.md

I added the sidebar "footer" text and updated it to use grid instead of flexbox...lmk what you think. 
Need to figure out how to do the "sticky" sidenav.

merged Ryan's updates, update markdown post template

---

src/markdown/articles/2018/year-one-retrospective-cj

Article post

---

src/components/organisms/Team/team_members.js
src/markdown/team/aragones-david.md

Add David bio

---

.gitignore
.vscode/launch.json
gatsby-config.js
gatsby-node.js
plugins/gatsby-source-sheets/gatsby-node.js
plugins/gatsby-source-sheets/getSheet.js
plugins/gatsby-source-sheets/package.json
src/components/templates/Careers/index.js
src/pages/docs.js

Hey @plhnk lets talk about how this works. You won't be able to run `npm run dev` it unless you have proper credentials.

google-sheets

---

package.json

Documentation here: https://www.gatsbyjs.org/docs/gatsby-cli/#options

update dev script to host on local ip

---

.gitignore
package-lock.json
package.json
plugins/gatsby-source-sheets/package-lock.json
src/components/molecules/AuthContainer/index.js
src/components/molecules/LogoutContainer/index.js
src/components/templates/PrivatePage/index.js
src/pages/blueprints/index.js
src/utils/index.js

needs to be tested in other browsers. Doesn't work in Brave browser. Errors throwing in dev reload. Everything else works though. Now it is a popup not a redirect

swap wedeploy auth with google auth

---

src/components/templates/Blueprints/styles.module.scss

scope Blueprints content template styles correctly

---

src/components/molecules/CardDefault/index.js
src/components/molecules/CardDefault/styles.module.scss
src/components/organisms/NavItems/styles.module.scss
src/components/organisms/Sidebar/index.js
src/components/organisms/Sidebar/styles.module.scss

- scoped sidebar styles to the js file
- improved contrast for navItems, added alt text for homepage images

finally solve all the bugs 🤞, improve accessibility

---

README.md
src/components/organisms/Team/team_members.js
src/markdown/team/hisamoto-naoki.md
src/markdown/team/ho-bryan.md
src/markdown/team/kim-sharon.md
src/markdown/team/lee-jessica.md
src/markdown/team/yang-julia.md
src/markdown/team/young-emily.md
src/markdown/team/yuan-rachel.md

@plhnk and @abelhancock 
I re-forked the repository and created individual commits for each team member.
I found out the problem with the `package-lock.json` probably occurred because I updated npm to a newer version.

Communication Design Team Bio

---

src/components/organisms/Team/team_members.js
src/markdown/team/cicero-emiliano.md

I'm just trolling him due to his laziness

Emiliano Cicero profile description. 

---

src/components/molecules/HeroPost/styles.module.scss
src/components/templates/Articles/styles.module.scss
src/components/templates/Careers/styles.module.scss
src/components/templates/Events/styles.module.scss
src/components/templates/Resources/styles.module.scss
src/components/templates/Team/index.js
src/components/templates/Team/styles.module.scss
src/theme/global.scss
src/theme/variables.scss

Child pages of:
- /articles
- /events 
- /team
Also added more beef to the line-height! #tripleStack #daveSpecial
cc @ryconn888

Make Mobile Great Again

---

src/components/atoms/Text/index.js
src/pages/newsletter/index.js

fix text component

---

src/components/molecules/ImageDownload/index.js
src/components/molecules/ImageDownload/styles.module.scss
src/markdown/blueprints/resources/iconography.mdx
src/markdown/blueprints/resources/illustrations.mdx
src/markdown/blueprints/resources/product-screens.mdx

- rewrite the way alt-text and download-name's are handled, less manual work for entering those in
- make 'download' button easier to use

Improve ImageDownloader component

---

src/components/templates/MainLayout/index.js
src/components/templates/Team/index.js
src/components/templates/Team/styles.module.scss
src/markdown/team/anton-juan.md
src/markdown/team/aragones-david.md
src/markdown/team/bargaid-duuriimaa.md
src/markdown/team/censi-andrea.md
src/markdown/team/cicero-emiliano.md
src/markdown/team/connolly-ryan.md
src/markdown/team/fernandes-vitor.md
src/markdown/team/hammer-markus.md
src/markdown/team/hanaoka-paul.md
src/markdown/team/hancock-abel.md
src/markdown/team/hidalgo-juan.md
src/markdown/team/himer-andras.md
src/markdown/team/hisamoto-naoki.md
src/markdown/team/ho-bryan.md
src/markdown/team/jeong-chris.md
src/markdown/team/kim-david.md
src/markdown/team/kim-sharon.md
src/markdown/team/lee-jessica.md
src/markdown/team/lyons-james.md
src/markdown/team/manso-miriam.md
src/markdown/team/pentz-patrick.md
src/markdown/team/valle-victor.md
src/markdown/team/vazquez-susana.md
src/markdown/team/wood-jon.md
src/markdown/team/yang-julia.md
src/markdown/team/young-emily.md
src/markdown/team/yuan-rachel.md

- just blaze 420
- add start year to team

Small, Fun Fixes

---

src/markdown/lexicon/satellite-components/sidebar/infopanel.md

Please see [LEXI-619](https://issues.liferay.com/browse/LEXI-619) for more information.

LEXI-619: Add a new section "Semantics" for Info Panel Page

---

src/markdown/careers/latam/product-designer.md
src/pages/index.js

remove Recife job posting

---

src/components/atoms/Image/index.js
src/components/molecules/Author/index.js
src/components/molecules/GlobalMdx/index.js
src/components/molecules/index.js
src/components/templates/Articles/index.js
src/components/templates/Blueprints/index.js
src/components/templates/Careers/index.js
src/components/templates/Events/index.js
src/components/templates/Handbook/index.js
src/components/templates/Lexicon-1/index.js
src/components/templates/Lexicon/index.js
src/components/templates/Lexicon/styles.module.scss
src/components/templates/Resources/index.js
src/components/templates/Team/index.js
src/markdown/articles/2019/design-at-scale-one-year-with-figma.mdx
src/markdown/blueprints/guidelines/iconography.mdx
src/markdown/blueprints/guidelines/logo-usage.mdx
src/markdown/lexicon/examples/asset-metrics-dashboard.mdx
src/markdown/lexicon/examples/document-preview.mdx
src/markdown/lexicon/examples/page-distribution.mdx
src/markdown/lexicon/examples/partner-portal.mdx
src/markdown/lexicon/examples/site-builder.mdx
src/theme/index.js

- add GlobalMdx component so you don't have to import common components (for now, Image and DoDont are globally available)
- create/improve Image component (see #517 for checklist)

Improve MDX experience

---

src/pages/resources/index.js

Follow https://github.com/liferay-design/liferay.design/issues/520

Placing Lexicon as first resource due to importance and use level

---

src/markdown/lexicon/patterns/actions-definition.mdx
src/markdown/lexicon/patterns/drag-and-drop.md
src/markdown/lexicon/patterns/index.md

Finally, we will use "Patterns" instead "Interaction"

LEXI-604: New Patterns section

---

gatsby-config.js
package-lock.json
package.json
src/components/atoms/CardGrid/index.js
src/components/atoms/Container/index.js
src/components/atoms/Icon/icons.js
src/components/atoms/Link/index.js
src/components/atoms/NiceLink/index.js
src/components/atoms/NiceLink/styles.module.scss
src/components/atoms/index.js
src/components/molecules/CardDefault/index.js
src/markdown/resources/figma.mdx
src/pages/events/index.js
src/pages/index.js
src/theme/global.scss
src/theme/index.js
static/images/icons/arrow.svg

- add Resources section to the homepage
- fix #520 and #526 
- add nice page transitions across the site

Friday Fun

---

src/components/molecules/FancyFooter/index.js
src/components/molecules/FancyFooter/styles.module.scss
src/components/molecules/SideTab/index.js
src/components/molecules/SideTab/styles.module.scss
src/components/molecules/index.js
src/components/organisms/Footer/index.js
src/components/organisms/HeroBanner/index.js
src/components/templates/Events/styles.module.scss
src/components/templates/MainLayout/index.js
src/pages/index.js

- fixes #543 and #386 (replaces Banner hiring ad w/a side tab - thx @pjpentz)
- adds fancy footer area (thx @ryconn888 )

Update Hiring Ad and add FancyFooter

---

src/components/atoms/CardGrid/index.js
src/components/atoms/Image/index.js
src/components/molecules/FancyFooter/index.js
src/components/molecules/SEO/index.js
src/components/molecules/index.js
src/components/templates/Articles/index.js
src/components/templates/Events/index.js
src/components/templates/Handbook/index.js
src/components/templates/Team/index.js
src/html.js
src/markdown/Authors.yaml
src/markdown/handbook/grow/product-design/engineering.md
src/markdown/handbook/grow/product-design/interaction.md
src/markdown/handbook/grow/product-design/introduction.md
src/markdown/handbook/grow/product-design/strategy.md

- made an <SEO> component so we can have more uniform improvements for shared links, fixes #565 
- added an evaluation table to the Product Design summary page
- prep for /handbook homepage

Improve SEO, Add Handbook Content

---

gatsby-config.js
package-lock.json
package.json
src/components/atoms/Link/index.js
src/components/molecules/CardAsset/index.js
src/components/molecules/Date/index.js
src/components/molecules/Date/styles.module.scss
src/components/molecules/SiteCredits/index.js
src/components/molecules/SocialIcons/index.js
src/components/molecules/index.js
src/components/organisms/ChangelogFeed/index.js
src/components/organisms/ChangelogFeed/styles.module.scss
src/components/templates/Events/index.js
src/components/templates/Events/styles.module.scss
src/components/templates/Lexicon-1/index.js
src/components/templates/Lexicon/index.js
src/markdown/handbook/welcome.mdx
src/markdown/lexicon/resources.mdx
src/pages/2018/index.js
src/pages/blueprints.js
src/pages/changelog.js
src/pages/lexicon-1.js
src/pages/lexicon.js
src/pages/principles/index.js
static/images/theme/handbook-frame.svg

- fix #570 
- style /changelog mostly to spec, thanks @davidhskim and @abelhancock 
- create <Date> for a reuse-able calendar icon

Polishing /handbook, /changelog

---

src/pages/2019/components/Carousel/index.js

make infinite pram false to fix mobile carousel #637

---

src/pages/design-week/components/Card/styles.module.scss
src/pages/design-week/index.js
src/pages/design-week/styles.module.scss

- improve animation — thanks @ryconn888 
- fix firefox button "issue" (#648) — thanks @jamesjlyons

Small Fixes

---

gatsby-config.js
gatsby-node.js
src/components/templates/MainLayout/index.js
src/components/templates/Newsletters/index.js
src/components/templates/index.js
src/pages/newsletter/Archive.js
src/pages/newsletter/styles.module.scss

Instead of sending people to Mailchimp hosted pages, let's keep them on our site!

Host our own Newsletter archive 

---

src/markdown/blueprints/guidelines/legal-notice.md

I updated the links for copyright to point to the relevant license policies.

Update links to internal copyright policies

---

src/components/organisms/CareerPathTracks/index.js
src/components/organisms/CareerPathTracks/styles.module.scss
src/components/templates/Handbook/index.js
src/markdown/handbook/grow/career-paths/evaluations.mdx
src/markdown/handbook/grow/communication-design.mdx
src/markdown/handbook/grow/core-skills.mdx
src/markdown/handbook/grow/introduction.mdx
src/markdown/handbook/grow/product-design.mdx
src/theme/documentation.module.scss

- fix broken links by removing them (content is available in a toggle so you don't have to go to another page)

Updates to handbook/grow

---

src/markdown/lexicon/core-components/table/index.mdx

- Fix some inconsistencies with documentation
- Delete attribute images

Update table content

---

src/markdown/handbook/lexicon.mdx

Just added a brief description of Lexicon and some important information to make it easier for onboarding new hires.

Adding a brief Lexicon introduction to handbook

---

src/markdown/lexicon/core-components/keys.md

Read [LEXI-954](https://issues.liferay.com/browse/LEXI-954)

LEXI-954: Clay link and typo

---

src/markdown/handbook/tools/liferay/installing-portal.md

I did all the process today in a new machine so it should work for everyone

Updates on the guide to install Portal

---

src/markdown/handbook/tools/liferay/installing-portal.md

Update tomcat number

---

src/markdown/Authors.yaml

updated profile links mphammer

---

src/components/molecules/SearchInput/index.js

creating this PR to see which people prefer

Idea: change lexicon search hotkey from "cmd + shift + f" to "/"

---

src/components/organisms/Footer/index.js
src/components/organisms/Footer/styles.module.scss

Reword it and added styles to make link easier to find. It was working in some places already

Text claim changes

---

src/components/organisms/CareerPathTracks/styles.module.scss
src/components/organisms/NavItems/index.js

https://issues.liferay.com/browse/LEXI-1042

Easier access to Lexicon that drives most of our traffic

---

src/markdown/lexicon/patterns/common-actions.md

Updating Create definition. New definition was there.

Updating create definition

---

src/components/organisms/Banner/styles.module.scss

Button text to be primary blue

---

src/components/organisms/HeroBanner/index.js

There are 3-4 job positions open now. The CTA was pointing to NA Senior PD

Pointing to careers page

---

src/components/atoms/PrivateComponent.js
src/components/molecules/AssetDownload/index.js
src/components/molecules/AssetDownload/styles.module.scss
src/components/molecules/AuthContainer/index.js
src/components/templates/Lexicon/index.js
src/markdown/blueprints/guidelines/logo-usage.mdx
src/pages/404.js
src/utils/index.js

- finishing touches on a number of issues
- start changes to PrivateComponent, now we have a global utility function `isAuthenticated()` to show / hide things based on if someone is signed in or not

Issue cleanup

---

src/markdown/lexicon/core-components/charts/chart-heatmap.md
src/markdown/lexicon/core-components/table/inline-edit-table.md
src/markdown/lexicon/patterns/common-actions.md
src/markdown/lexicon/patterns/common-content-patterns.md
src/markdown/lexicon/writing/index.md
src/markdown/lexicon/writing/principles.mdx
src/markdown/lexicon/writing/style.mdx
src/markdown/lexicon/writing/writing-framework.mdx

@drakonux as accorded in our last meeting and to reduce confusion.

Adding pending status to writing pages

---

src/components/atoms/Container/index.js
src/components/templates/MainLayout/index.js
src/markdown/careers/apac/senior-product-designer-2021-02-03.md
src/markdown/careers/latam/senior-communication-designer.md
src/markdown/careers/latam/senior-designer-design-ops.md
src/markdown/careers/na/product-designer-dxp.md
src/markdown/careers/na/senior-communication-designer.md
src/pages/office-hours/components/Card.js
src/pages/office-hours/index.js
src/utils/index.js
static/admin/config.yml

- add all the new open positions! 🙌 
- fix a bunch of random console errors for a better DX, faster builds

/careers update 🙌 

---

src/pages/office-hours/components/Card.js
src/utils/index.js

feature: add time zones and clean up display on /office-hours

---

src/markdown/careers/emea/principal-communication-designer.md

Language requirement for Ppal Comm Des Spain

---

src/markdown/careers/latam/product-designer-2020-02-22.md

Hiding mid level position in Brazil

Update careers page

---

src/components/templates/Careers/index.js
src/markdown/Offices.yaml
src/markdown/careers/latam/senior-communication-designer.md

@plhnk I've added a small change to reflect 
"Remote in LATAM, based in Mexico City, Mexico"

Sr cmm d jd

---

src/markdown/handbook/tools/liferay/installing-portal.md

Update guide with more tips and details

Update guide with more tips and details

---

src/markdown/careers/emea/senior-product-designer-2021-12-22.md

Please wait until we have the letter signed to merge this

Hiding Sr PD DXPC

---

src/markdown/handbook/tools/jira/issues/communication-design-request.md
src/markdown/handbook/tools/jira/issues/epic.md
src/markdown/handbook/tools/jira/issues/lexicon.md
src/markdown/handbook/tools/jira/issues/story.md
src/markdown/handbook/tools/jira/issues/user-testing.md
src/markdown/handbook/tools/jira/issues/webinar.md
src/markdown/handbook/tools/jira/overview.md

Content adjustment for issue types in Jira.

Content adjustment

---

src/markdown/handbook/tools/google-calendar.mdx

[Unified Department Calendar](https://issues.liferay.com/browse/DESIGN-54)
Parent Ticket
[Document Purpose and Use of Design Calendar](https://issues.liferay.com/browse/DESIGN-56)
Add documentation to handbook

Add division and department calendar documentation

---

src/markdown/handbook/tools/jira/story-points.md

Content related to story points and effort estimation.

Create Story Points Documentation (first draft)

---

src/markdown/Authors.yaml
src/markdown/handbook/tools/jira/issues/webinar.md

Webinar documentation is updated in Handbook and links to Confluence and Blueprints (More complete)
Marleny's title is updated to Senior Communication Designer

Update Documentation and Liferay.Design Profiles

---

src/markdown/Authors.yaml
src/markdown/careers/emea/associate-product-designer-it-2022-07-07.md
src/markdown/careers/emea/senior-product-designer-es-2022-08-05.md
src/markdown/careers/latam/senior-product-designer-br-2022-08-01.md

In addition to updating titles and career openings:
**Create consistency between titles**
- Format is Manager/Direction, Department (Senior Manager, Product Design)
- Spell out words (Senior instead of Sr.)
**Alphabetize Authors.yaml**

Update titles and career openings

---

src/markdown/lexicon/core-components/empty-states.md

We're making the title a required prop so I've updated the content with the new information and removed some old ones.

Updated the empty state's page

---

src/markdown/careers/latam/manager-product-design-br-2022-09-05.md

Remove Product Design Manager BR position from careers
https://liferay.design/careers/latam/manager-product-design-br-2022-09-05/

Unpublish Product Design Manager position from careers

---

src/components/templates/Careers/index.js
src/markdown/careers/latam/product-designer.md
src/markdown/careers/latam/web-solutions-designer-pe-2023-06-01.md

Careers Update

---

src/markdown/careers/latam/web-solutions-designer-pe-2023-06-01.md
src/markdown/careers/na/freelance-product-designer.md

Remove Web Solutions Designer position based out of Peru.

Unpublish Web Solutions Designer position

---

src/markdown/Authors.yaml
static/_redirects

- formatting / updating the list of designers
- add redirects for new brand site

Farewell liferay

---

src/markdown/handbook/resources.mdx

Update of the Blueprint URL to the Liferay new Brand site

Update Blueprints URL

---

src/pages/resources/index.js

Replace the text of Blueprints with Brand and the new URL

Update Brand URL in Resources page

---

src/components/templates/Handbook/Welcome/index.js

Update the Blueprint template with the new URL to the Brand site

Update Handbook Blueprint Template

---

src/components/molecules/AuthContainer/index.js

Make sign in accessible by keyboard

---

src/components/organisms/NavItems/index.js
src/components/organisms/Navbar/index.js
src/components/templates/Blueprints/index.js
src/components/templates/Handbook/index.js
src/components/templates/Lexicon-1/index.js
src/components/templates/Lexicon/index.js
src/components/templates/PrivatePage/index.js

The current implementation of login authentication is not used in practice.
It can also cause legal issues with cookies, so it is disabled at least temporarily. This commit should be the reference if we need to recover it for any reason.

Remove Login Button
